#!/usr/bin/env python

import json

models = [
    'FC-DenseNet56', 'Encoder-Decoder', 'Encoder-Decoder-Skip',
    'RefineNet-Res50', 'FRRN-A', 'FRRN-B', 'MobileUNet',
    'MobileUNet-Skip', 'PSPNet-Res50', 'GCN-Res50', 'DeepLabV3-Res50
    DeepLabV3_plus-Res50', 'AdapNet'
]
model_s3_uri = 's3://nad-sandbox/jobs/Semantic-Segmentation-Suite/code'
dataset_name = 'dataset-HT'

output = []

for model in models[2:]:
    d = {
        'model-name': model,
        'model-s3-uri': model_s3_uri,
        'dataset-name': dataset_name
    }

    output.append(d)

print(json.dumps(output))
